# Workflow name
name: "NPM Publish"

# Event for the workflow
on:
  release:
    types: [published]

# List of jobs
jobs:
  release:
    runs-on: ubuntu-latest
    if: endsWith(github.event.release.tag_name, '-npm') || endsWith(github.event.release.tag_name, '-npm-dry-run')
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: rm package-lock.json && npm install
        working-directory: .
      - name: Build the app
        run: npm run build
        working-directory: .
      - name: Publish to npm
        run: |
          if [[ ${{ github.event.release.tag_name }} == *-npm-dry-run ]]; then
            npm publish --dry-run
          elif [[ ${{ github.event.release.tag_name }} == *-npm ]]; then
            npm publish
          fi
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
